require("vishakh.remap")
require("vishakh.set")
require("vishakh.snippet")
require("vishakh.folding")
require("vishakh.terminal")
require("vishakh.filetype")
require("vishakh.comments")
vim.lsp.set_log_level("debug")
